server:
  port: 8080
spring:
  profiles:
    active: jdbc
# thymeleaf配置
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
    cache: false

#mybatis配置
mybatis:
  type-aliases-package: com.janti
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
#  mapper-locations: classpath:com/janti/dao/*.xml

redis:
  # Redis服务器地址
  host: 127.0.0.1
  # Redis服务器连接端口
  port: 6379
  # 连接超时时间（毫秒）
  timeout: 10
  # 连接池中的最大空闲连接
  maxIdle: 8
  # 连接池中的最小空闲连接
  minIdle: 0
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  maxWait: 500
  # 连接池最大连接数（使用负值表示没有限制）
  maxTotal: 10